version: '2.1'

services: 
  nocodb: 
    depends_on: 
      root_db: 
        condition: service_healthy
    environment: 
      # Accessing the DB via its service name
      NC_DB: "pg://root_db:5432?u=postgres&p=password&d=root_db"
    image: "nocodb/nocodb:latest"
    ports: 
      - "6626:8080" # Optional: remove this if you only use Cloudflare
    restart: always
    volumes: 
      - /Users/Shared/workdir/nocodb/nc:/usr/app/data

  root_db: 
    image: postgres:16.6
    # giving it a specific name makes it easier to type in UI Bakery
    container_name: noco_postgres 
    restart: always
    environment: 
      POSTGRES_DB: root_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    healthcheck: 
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      timeout: 2s
    volumes: 
      - /Users/Shared/workdir/nocodb/db:/var/lib/postgresql/data

# The Magic Block
networks:
  default:
    name: one-network-to-rule-them-all
    external: true
